openapi: 3.0.0
info:
  title: Notification API
  version: 1.0.0
  description: API documentation for Notification microservice
servers:
  - url: /api/v1
paths:
  /notifications:
    get:
      summary: Get all notifications
      tags:
        - Notification
      responses:
        '200':
          description: A list of notifications
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: success
                  message:
                    type: string
                    example: Success!
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/Notification'
                  appCode:
                    type: string
                    example: OK
                  timestamp:
                    type: string
                    example: '2023-10-01T12:00:00.000Z'
    post:
      summary: Create a new notification
      tags:
        - Notification
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewNotification'
      responses:
        '201':
          description: The created notification
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: success
                  message:
                    type: string
                    example: Notification created successfully
                  data:
                    $ref: '#/components/schemas/Notification'
                  appCode:
                    type: string
                    example: OK
                  timestamp:
                    type: string
                    example: '2023-10-01T12:00:00.000Z'
  /notifications/{id}:
    get:
      summary: Get a specific notification by ID
      tags:
        - Notification
      parameters:
        - in: path
          name: id
          required: true
          description: ID of the notification to get
          schema:
            type: string
      responses:
        '200':
          description: The requested notification
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: success
                  message:
                    type: string
                    example: Success!
                  data:
                    $ref: '#/components/schemas/Notification'
                  appCode:
                    type: string
                    example: OK
                  timestamp:
                    type: string
                    example: '2023-10-01T12:00:00.000Z'
        '404':
          description: Notification not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: error
                  message:
                    type: string
                    example: Notification not found
                  appCode:
                    type: string
                    example: UNKNOWN_ERROR
                  timestamp:
                    type: string
                    example: '2023-10-01T12:00:00.000Z'
    put:
      summary: Update an existing notification by ID
      tags:
        - Notification
      parameters:
        - in: path
          name: id
          required: true
          description: ID of the notification to update
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Notification'
      responses:
        '200':
          description: The updated notification
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: success
                  message:
                    type: string
                    example: Notification updated successfully
                  data:
                    $ref: '#/components/schemas/Notification'
                  appCode:
                    type: string
                    example: OK
                  timestamp:
                    type: string
                    example: '2023-10-01T12:00:00.000Z'
        '404':
          description: Notification not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: error
                  message:
                    type: string
                    example: Notification not found
                  appCode:
                    type: string
                    example: UNKNOWN_ERROR
                  timestamp:
                    type: string
                    example: '2023-10-01T12:00:00.000Z'
    delete:
      summary: Delete a notification by ID
      tags:
        - Notification
      parameters:
        - in: path
          name: id
          required: true
          description: ID of the notification to delete
          schema:
            type: string
      responses:
        '204':
          description: Successfully deleted
        '404':
          description: Notification not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: error
                  message:
                    type: string
                    example: Notification not found
                  appCode:
                    type: string
                    example: UNKNOWN_ERROR
                  timestamp:
                    type: string
                    example: '2023-10-01T12:00:00.000Z'
components:
  schemas:
    Notification:
      type: object
      properties:
        _id:
          type: string
          example: '60c72b2f9b1d8f0d8d0b6f9e'
        userId:
          type: string
          example: '60c72b2f9b1d8f0d8d0b6f9f'
        config:
          type: object
          properties:
            email:
              type: boolean
              example: true
        type:
          type: string
          example: 'itinerary comment'
        resourceId:
          type: string
          example: '60c72b2f9b1d8f0d8d0b6fa0'
        notificationStatus:
          type: string
          example: 'NOT SEEN'
        createdAt:
          type: string
          format: date-time
          example: '2023-10-01T12:00:00.000Z'
      required:
        - userId
        - config
        - type
        - resourceId
        - notificationStatus
    NewNotification:
      type: object
      properties:
        userId:
          type: string
          example: '60c72b2f9b1d8f0d8d0b6f9f'
        config:
          type: object
          properties:
            email:
              type: boolean
              example: true
        type:
          type: string
          example: 'itinerary comment'
        resourceId:
          type: string
          example: '60c72b2f9b1d8f0d8d0b6fa0'
        notificationStatus:
          type: string
          example: 'NOT SEEN'
      required:
        - userId
        - config
        - type
        - resourceId
        - notificationStatus