name: Generate a develop version in Docker Hub

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  upload-to-docker-hub:
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis:latest
        ports:
          - 6379:6379
        options: --health-cmd="redis-server --version" --health-timeout=5s --health-retries=3

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile
          push: true
          tags: javifdez7/horizon-notifications:develop

      # Add this step to wait for Redis to be ready
      - name: Wait for Redis to be ready
        run: |
          for i in {1..30}; do
            if redis-cli -h 127.0.0.1 -p 6379 PING; then
              echo "Redis is ready!";
              break;
            fi
            echo "Waiting for Redis to be ready...";
            sleep 2;
          done

      - name: Run tests
        run: |
          npm install
          npm run test
